[project]
name = "temporal-starter-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask[async]>=3.1.1",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.30",
    "temporalio>=1.15.0",
]
