model_config:
  - provider: "openai"
    model: "gpt-4o"
    enabled: false
  - provider: "openai"
    model: "gpt-5"
    enabled: true
  - provider: "anthropic"
    model: "claude-sonnet-4-20250514"
    enabled: false
  - provider: "anthropic"
    model: "claude-sonnet-4-5-20250929"
    enabled: false
  - provider: "ollama"
    model: "gpt-oss:20b"
    enabled: false
    is_local: true
    base_url: "http://127.0.0.1:8080/v1"
    # run locally using $ llama-server -hf ggml-org/gpt-oss-20b-GGUF -c 32768
  - provider: "ollama"
    model: "qwen3:1.7b-q8_0"
    enabled: true
    is_local: true
    base_url: "http://127.0.0.1:8080/v1"
    # run locally using $ llama-server -hf Qwen/Qwen3-1.7B-GGUF:Q8_0 -c 32768
  - provider: "ollama"
    model: "microsoft/Phi-3-mini-4k-instruct"
    enabled: false
    is_local: true
    base_url: "http://127.0.0.1:8080/v1"
    # run locally using $ llama-server -hf microsoft/Phi-3-mini-4k-instruct-gguf -c 32768
mcp_config:
  general:
    filesystem:
      enabled: true
    search:
      enabled: true
    code_execution:
      enabled: true
    datetime:
      enabled: true
  productivity:
    todo:
      todoist:
        enabled: false
    calendar:
      google_calendar:
        enabled: false
        higher_order_tools_enabled: false
      clockwise:
        enabled: false
        higher_order_tools_enabled: false
    chat:
      slack:
        enabled: false
        auth_method: "xoxp"
        higher_order_tools_enabled: false
    notes:
      obsidian:
        enabled: false
    meeting_transcript:
      loom:
        enabled: false
      zoom:
        enabled: false
chat:
  slack:
    use_local_model: false
    project_to_channels: {
      "foo": ["bar", "baz"]
    }
    team_to_channels: {
      "foo": ["bar", "baz"]
    }
notes:
  obsidian:
    default_vault_name: "personal_notes"
    vault_configurations:
      - vault_name: "personal_notes"
        vault_path: "/path/to/personal_notes"
        vector_db_collection: "personal_notes"
        vector_db_path: "/tmp/data/chroma/personal_notes"
        exclude_dirs: ["ignore"]
        exclude_files: ["ignore.md"]
        num_results: 3
meeting_transcript:
  zoom:
    storage_dir: "/path/to/zoom_transcripts"
    use_local_model: true
    max_transcript_size: 32000 # 0 means no limit, otherwise token limit
  loom:
    storage_dir: "/path/to/loom_transcripts"
    use_local_model: true
    max_transcript_size: 32000 # 0 means no limit, otherwise token limit
debug:
  inspect_tools: true