model_config:
  - provider: "openai"
    model: "gpt-4o"
    enabled: false
  - provider: "openai"
    model: "gpt-5"
    enabled: true
  - provider: "anthropic"
    model: "claude-sonnet-4-20250514"
    enabled: false
  - provider: "anthropic"
    model: "claude-sonnet-4-5-20250929"
    enabled: false
  - provider: "ollama"
    model: "gpt-oss:20b"
    enabled: false
    is_local: true
    base_url: "http://127.0.0.1:8080/v1"
    # run locally using $ llama-server -hf ggml-org/gpt-oss-20b-GGUF -c 32768
  - provider: "ollama"
    model: "qwen3:1.7b-q8_0"
    enabled: true
    is_local: true
    base_url: "http://127.0.0.1:8080/v1"
    # run locally using $ llama-server -hf Qwen/Qwen3-1.7B-GGUF:Q8_0 -c 32768
  - provider: "ollama"
    model: "microsoft/Phi-3-mini-4k-instruct"
    enabled: false
    is_local: true
    base_url: "http://127.0.0.1:8080/v1"
    # run locally using $ llama-server -hf microsoft/Phi-3-mini-4k-instruct-gguf -c 32768
chat:
  slack:
    use_local_model: false
    project_to_channels: {
      "foo": ["bar", "baz"]
    }
    team_to_channels: {
      "foo": ["bar", "baz"]
    }
notes:
  obsidian:
    default_vault_name: "personal_notes"
    vault_configurations:
      - vault_name: "personal_notes"
        vault_path: "/path/to/personal_notes"
        vector_db_collection: "personal_notes"
        vector_db_path: "/tmp/data/chroma/personal_notes"
        exclude_dirs: ["ignore"]
        exclude_files: ["ignore.md"]
        num_results: 3
meeting_transcript:
  zoom:
    storage_dir: "/path/to/zoom_transcripts"
    use_local_model: true
    max_transcript_size: 32000 # 0 means no limit, otherwise token limit
  loom:
    storage_dir: "/path/to/loom_transcripts"
    use_local_model: true
    max_transcript_size: 32000 # 0 means no limit, otherwise token limit
debug:
  inspect_tools: true
mcp_config:
  general:
    filesystem:
      enabled: true
    search:
      enabled: true
    code_execution:
      enabled: true
    datetime:
      enabled: true
  productivity:
    todo:
      todoist:
        enabled: false
    calendar:
      google_calendar:
        enabled: false
        higher_order_tools_enabled: false
      clockwise:
        enabled: false
        higher_order_tools_enabled: false
    chat:
      slack:
        enabled: false
        auth_method: "xoxp"
        higher_order_tools_enabled: false
    notes:
      obsidian:
        enabled: false
    meeting_transcript:
      loom:
        enabled: false
      zoom:
        enabled: false
  sde:
    project_management:
      jira:
        enabled: false
        higher_order_tools_enabled: false
      linear:
        enabled: false
        higher_order_tools_enabled: false
      github:
        enabled: false
        higher_order_tools_enabled: false
    git:
      github:
        enabled: false
        higher_order_tools_enabled: false
    container:
      docker:
        enabled: false
        higher_order_tools_enabled: false
      k8s:
        enabled: false
        higher_order_tools_enabled: false
    observability:
      prometheus:
        enabled: false
        higher_order_tools_enabled: false
  allowed_tool_prefixes:
    - docker
    - k8s
    - github
    - jira
    - confluence
    - linear
  allowed_tools:
    docker:
    - docker_list_containers
    - docker_start_container
    - docker_stop_container
    - docker_list_images
    - docker_list_networks
    - docker_list_volumes
    k8s:
    - k8s_get-k8s-resource
    - k8s_list-k8s-namespaces
    - k8s_list-k8s-nodes
    - k8s_list-k8s-resources
    github:
    - github_add_issue_comment
    - github_create_branch
    - github_create_issue
    - github_create_pull_request
    - github_get_commit
    - github_get_file_contents
    - github_get_issue
    - github_get_issue_comments
    - github_get_label
    - github_get_tag
    - github_get_me
    - github_list_commits
    - github_list_issues
    - github_list_label
    - github_list_pull_requests
    - github_list_tags
    - github_pull_request_read
    - github_pull_request_review_write
    - github_search_code
    - github_search_issues
    - github_search_pull_requests
    - github_search_repositories
    - github_search_users
    - github_update_issue
    - github_update_pull_request
    jira:
    - jira_atlassianUserInfo
    - jira_getAccessibleAtlassianResources
    - jira_searchJiraIssuesUsingJql
    - jira_getJiraIssue
    - jira_editJiraIssue
    - jira_getTransitionsForJiraIssue
    - jira_transitionJiraIssue
    - jira_lookupJiraAccountId
    - jira_addCommentToJiraIssue
    - jira_getVisibleJiraProjects
    confluence:
    - confluence_atlassianUserInfo
    - confluence_getAccessibleAtlassianResources
    - confluence_getConfluenceSpaces
    - confluence_getConfluencePage
    - confluence_getPagesInConfluenceSpace
    - confluence_createConfluenceFooterComment
    - confluence_createConfluenceInlineComment
    - confluence_searchConfluenceUsingCql
    - confluence_createConfluencePage
    - confluence_updateConfluencePage
    linear:
    - linear_get_issue
    - linear_list_issues
    - linear_create_issue
    - linear_update_issue
    - linear_get_issue_status
    - linear_list_issue_labels
    - linear_create_issue_label
    - linear_list_projects
    - linear_get_project
  unused_tools:
    docker:
    - docker_create_container
    - docker_run_container
    - docker_recreate_container
    - docker_fetch_container_logs
    - docker_remove_container
    - docker_pull_image
    - docker_push_image
    - docker_build_image
    - docker_remove_image
    - docker_create_network
    - docker_remove_network
    - docker_list_volumes
    - docker_create_volume
    - docker_remove_volume
    k8s:
    - k8s_apply-k8s-resource
    - k8s_get-k8s-pod-logs
    - k8s_k8s-pod-exec
    - k8s_list-k8s-contexts
    - k8s_list-k8s-events
    - k8s_list-k8s-nodes
    github:
    - github_add_comment_to_pending_review
    - github_add_sub_issue
    - github_assign_copilot_to_issue
    - github_create_or_update_file
    - github_create_repository
    - github_delete_file
    - github_fork_repository
    - github_get_latest_release
    - github_get_release_by_tag
    - github_get_team_members
    - github_get_teams
    - github_list_branches
    - github_list_issue_types
    - github_list_releases
    - github_list_sub_issues
    - github_merge_pull_request
    - github_push_files
    - github_remove_sub_issue
    - github_reprioritize_sub_issue
    - github_request_copilot_review
    - github_update_pull_request_branch
    jira:
    - jira_createJiraIssue
    - jira_search
    - jira_fetch
    - jira_getJiraProjectIssueTypesMetadata
    - jira_getJiraIssueTypeMetaWithFields
    - jira_getJiraIssueRemoteIssueLinks
    confluence:
    - confluence_getConfluencePageFooterComments
    - confluence_getConfluencePageInlineComments
    - confluence_getConfluencePageDescendants
    linear:
    - linear_list_comments
    - linear_create_comment
    - linear_list_cycles
    - linear_get_document
    - linear_list_documents
    - linear_list_issue_statuses
    - linear_create_project
    - linear_update_project
    - linear_list_project_labels
    - linear_list_teams
    - linear_get_team
    - linear_list_users
    - linear_get_user
    - linear_search_documentation
